kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  namespace: "{{ .Values.global.namespace }}"
  annotations:
    installdate: {{ dateInZone "2006-01-02T15:04:05" (now) "UTC" }}
  labels:
    app: "{{ .Values.global.label.app }}"
    version: "{{ .Chart.Version }}"
data:
  pipeline-write-metrics-active: "{{ .Values.catalog.pipeline.config.writemetricsactive | default .Values.catalogDefaults.pipeline.config.writemetricsactive }}"
