apiVersion: v2
name: "build-golang-0.1" 
version: 0.1.0
description: tekton pipeline build golang
type: application
keywords:
  - ci
  - cd
  - tekton
  - pipeline
home: ttps://github.com/Continuous-X
sources:
  - ttps://github.com/Continuous-X/cx-tekton-catalog.git
appVersion: 1.0.0
deprecated: false