apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-catalog
spec:
  workspaces:
    - name: source
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi8/ubi-micro:latest
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        set -xe
        echo "Hello World!"

        id
        ls -la
