apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-golang
spec:
  params:
    - name: git-url
    - name: git-revision
  resources:
    - name: pipeline-resource-type
      type: pipeline-type
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
      - name: url
        value: "$(params.git-url)"
      - name: revision
        value: "$(params.git-revision)"
      workspaces:
        - name: output
          workspace: source
