apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ci-golang
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: staging
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-golang-
        labels:
          tekton.dev/pipeline: ci-golang
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: ci-golang
        params:
          - name: github-repo-url
            value: '$(tt.params.gitrepositoryurl)'
          - name: github-repo-revision
            value: '$(tt.params.gitrevision)'
