apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ci-golang-push-all-0.1
spec:
  serviceAccountName: pipeline
  triggers:
    - name: ci-golang-0.1
      bindings:
        - ref: ci-golang-0.1
      template:
        ref: ci-golang-0.1